name: Deploy blog source to github pages

on: 
  push:
    branches:
      - react
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@react
      
    - name: build and deploy
      uses: JamesIves/github-pages-deploy-action@react
      env:
          ACCESS_TOKEN: ${{ secrets.Deploy_Access_Token }}
          BRANCH: master
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run pub
